Vagrant.configure("2") do |config|

  # OMD host
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.hostname = "monitoring.example.com"
    monitoring.vm.box = "centos/7"
    # forward some ports
    monitoring.vm.network "forwarded_port", guest: 80, host: 8080
    monitoring.vm.network "forwarded_port", guest: 443, host: 8443
    monitoring.vm.network "forwarded_port", guest: 5665, host: 8665
    # add private network
    monitoring.vm.network "private_network", ip: "192.168.23.10"

    # install Ansible and configure system
    monitoring.vm.provision "shell", inline: <<-SHELL
      yum -y install rpm-python epel-release python-xml
      # ensure to update to latest EPEL and ansible release
      yum -y install epel-release ansible
    SHELL
    monitoring.vm.provision "ansible_local" do |ansible|
      ansible.galaxy_role_file = "requirements_monitoring.yml"
      ansible.playbook = "playbook_monitoring.yml"
    end
  end

  # Zabbix host
  config.vm.define "zabbix", autostart: false do |zabbix|
    zabbix.vm.hostname = "zabbix.example.com"
    zabbix.vm.box = "centos/7"
    # forward some ports
    zabbix.vm.network "forwarded_port", guest: 80, host: 8081
    zabbix.vm.network "forwarded_port", guest: 443, host: 8444
    # add private network
    zabbix.vm.network "private_network", ip: "192.168.23.20"

    # install Ansible and configure system
    zabbix.vm.provision "shell", inline: <<-SHELL
      yum -y install rpm-python epel-release python-xml
      # ensure to update to latest EPEL and ansible release
      yum -y install epel-release ansible
    SHELL
    zabbix.vm.provision "ansible_local" do |ansible|
      ansible.galaxy_role_file = "requirements_zabbix.yml"
      ansible.playbook = "playbook_zabbix.yml"
    end
  end

  # Xen host running a VM
  config.vm.define "xen", autostart: false do |xen|
    xen.vm.hostname = "xen.example.com"
    xen.vm.box = "centos/7"
    # add private network
    xen.vm.network "private_network", ip: "192.168.23.30"

    # install Ansible and configure system
    xen.vm.provision "shell", inline: <<-SHELL
      yum -y install rpm-python epel-release python-xml
      # ensure to update to latest EPEL and ansible release
      yum -y install epel-release ansible
    SHELL
    xen.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook_xen.yml"
    end
  end

  # KVM host running a VM
  config.vm.define "kvm" do |kvm|
    kvm.vm.hostname = "kvm.example.com"
    kvm.vm.box = "centos/7"
    # add private network
    kvm.vm.network "private_network", ip: "192.168.23.40"

    # install Ansible and configure system
    kvm.vm.provision "shell", inline: <<-SHELL
      yum -y install rpm-python epel-release python-xml
      # ensure to update to latest EPEL and ansible release
      yum -y install epel-release ansible
    SHELL
    kvm.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook_kvm.yml"
    end
  end
  
  # vSphere host running a VM
    config.vm.define "esxi", autostart: false do |esxi|
    esxi.vm.hostname = "esxi.example.com"
    esxi.vm.box = "vmware/esxi"
    # forward some ports
    esxi.vm.network "forwarded_port", guest: 80, host: 8082
    esxi.vm.network "forwarded_port", guest: 443, host: 8445
    # add private network
    esxi.vm.network "private_network", ip: "192.168.23.50"

    # configure system
    # TODO: but how though?
  end

  # Foreman/Katello host
  config.vm.define "katello" do |katello|
    katello.vm.hostname = "katello.example.com"
    katello.vm.box = "centos/7"
    # forward some ports
    katello.vm.network "forwarded_port", guest: 80, host: 8083
    katello.vm.network "forwarded_port", guest: 443, host: 8446
    # add private network
    katello.vm.network "private_network", ip: "192.168.23.60"
      # set memory
    katello.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
    end

    # install Ansible and configure system
    katello.vm.provision "shell", inline: <<-SHELL
      yum -y install rpm-python epel-release python-xml
      # ensure to update to latest EPEL and ansible release
      yum -y install epel-release ansible
    SHELL
    katello.vm.provision "ansible_local" do |ansible|
      ansible.galaxy_role_file = "requirements_katello.yml"
      ansible.playbook = "playbook_katello.yml"
    end
  end

  # Uyuni host
  config.vm.define "uyuni" do |uyuni|
    uyuni.vm.hostname = "uyuni.example.com"
    uyuni.vm.box = "generic/opensuse15"
    # copy files
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    # forward some ports
    uyuni.vm.network "forwarded_port", guest: 80, host: 8084
    uyuni.vm.network "forwarded_port", guest: 443, host: 8447
    # add private network
    uyuni.vm.network "private_network", ip: "192.168.23.70"
    # set memory
    uyuni.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    # install Ansible and configure system
    uyuni.vm.provision "shell", inline: <<-SHELL
      zypper --non-interactive install python2-rpm ansible python-xml
    SHELL
    uyuni.vm.provision "ansible_local" do |ansible|
      ansible.galaxy_role_file = "requirements_uyuni.yml"
      ansible.galaxy_roles_path = "/etc/ansible/roles"
      ansible.galaxy_command = "sudo ansible-galaxy install -i --role-file=%{role_file} --roles-path=%{roles_path}"
      ansible.playbook = "playbook_uyuni.yml"
    end
  end
end